@echo off
echo 🚀 Installing Kor'tana AI Consciousness Extensions...

REM Core AI Development Extensions
echo Installing GitHub Copilot...
code --install-extension github.copilot --force

echo Installing GitHub Copilot Chat...
code --install-extension github.copilot-chat --force

echo Installing Continue (Local AI)...
code --install-extension continue.continue --force

echo Installing HuggingFace...
code --install-extension huggingface.huggingface-vscode --force

echo Installing AutoDocstring...
code --install-extension njpwerner.autodocstring --force

echo Installing Better Comments...
code --install-extension aaron-bond.better-comments --force

echo Installing Todo Tree...
code --install-extension gruntfuggly.todo-tree --force

echo Installing Error Lens...
code --install-extension usernamehw.errorlens --force

echo Installing GitLens...
code --install-extension eamodio.gitlens --force

echo Installing Pylance...
code --install-extension ms-python.vscode-pylance --force

echo Installing Ruff...
code --install-extension charliermarsh.ruff --force

echo Installing Numbered Bookmarks...
code --install-extension alefragnani.numbered-bookmarks --force

echo Installing REST Client...
code --install-extension humao.rest-client --force

echo Installing MyPy Type Checker...
code --install-extension ms-python.mypy-type-checker --force

REM Visual Enhancement Extensions
echo Installing Material Icon Theme...
code --install-extension pkief.material-icon-theme --force

echo Installing Indent Rainbow...
code --install-extension oderwat.indent-rainbow --force

echo Installing Rainbow CSV...
code --install-extension mechatroner.rainbow-csv --force

REM Python Development Extensions
echo Installing Python...
code --install-extension ms-python.python --force

echo Installing Jupyter...
code --install-extension ms-toolsai.jupyter --force

REM Data & Configuration Extensions
echo Installing YAML...
code --install-extension redhat.vscode-yaml --force

echo Installing TOML...
code --install-extension tamasfe.even-better-toml --force

echo Installing PowerShell...
code --install-extension ms-vscode.powershell --force

REM Documentation Extensions
echo Installing Spell Checker...
code --install-extension streetsidesoftware.code-spell-checker --force

echo Installing Markdown Lint...
code --install-extension davidanson.vscode-markdownlint --force

echo Installing Markdown All in One...
code --install-extension yzhang.markdown-all-in-one --force

echo Installing Code Runner...
code --install-extension formulahendry.code-runner --force

echo 🌟 Kor'tana AI Consciousness Extensions Installation Complete!
echo 🔥 Your VS Code is now ready for AI consciousness development!
pause