[pytest]
addopts = 
    --ignore=archive_2025_05_30
    --ignore=archive
    --ignore=obsolete
    -v
pythonpath = src
testpaths = tests .
python_files = test_*.py
python_classes = Test*
python_functions = test_*
