"""create_core_memories_table

Revision ID: 312cfdf7bc63
Revises:
Create Date: 2025-06-04 08:13:47.863826

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "312cfdf7bc63"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
