"""
PR Creation Router for Kor'tana Autonomous System

Handles automatic PR creation from completed task branches.
"""

import os
from datetime import datetime
from typing import Any

import requests
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from src.kortana.config import get_settings
from src.kortana.database import get_db
from src.kortana.logger import setup_logging
from src.kortana.models import GitHubTask

router = APIRouter()
logger = setup_logging()


class PRCreationError(Exception):
    """Raised when PR creation fails"""

    pass


class PRCreator:
    """Automated PR creation from task branches"""

    def __init__(self, db: Session):
        self.db = db
        self.token = None

    def _validate_token(self) -> bool:
        """Validate GitHub token is configured"""
        token = os.environ.get("GITHUB_TOKEN")
        if token is None:
            token = get_settings().GITHUB_TOKEN

        if not token:
            raise PRCreationError("GitHub token not configured for PR creation")
        self.token = token
        return True

    def _get_repo_info(self, repo: str):
        """Parse repo string into owner and name"""
        parts = str(repo).split("/")
        if len(parts) < 2:
            raise PRCreationError(f"Invalid repo format: {repo}")
        return parts[-2], parts[-1]

    def _generate_pr_description(self, task: GitHubTask, code_changes=None) -> str:
        """Generate PR description from task information"""
        description = f"""## Summary
- **Issue:** Issue #{task.github_issue_number}
- **Status:** {task.status}
- **Priority:** {task.priority}

## Changes

{task.description or "No description provided."}

## Analysis

{task.analysis or "No analysis available."}

## Plan

{task.plan or "No plan available."}

## Files Changed

"""

        if isinstance(code_changes, str):
            description += f"{code_changes}\n\n"
        elif code_changes and isinstance(code_changes, dict):
            if code_changes.get("created"):
                description += "### Created\n"
                for f in code_changes["created"]:
                    description += f"- `{f}`\n"
                description += "\n"

            if code_changes.get("modified"):
                description += "### Modified\n"
                for f in code_changes["modified"]:
                    description += f"- `{f}`\n"
                description += "\n"

            if code_changes.get("deleted"):
                description += "### Deleted\n"
                for f in code_changes["deleted"]:
                    description += f"- `{f}`\n"
                description += "\n"
        else:
            description += "_Files changed information not available_\n\n"

        description += """## Testing

- [ ] Tests pass locally
- [ ] Manual testing completed
- [ ] Edge cases considered

## Checklist

- [ ] Code follows project style guidelines
- [ ] Documentation updated
- [ ] Tests added/updated
- [ ] No breaking changes

---

*Auto-generated by Kor'tana Autonomous System*
"""
        return description

    def create_pr(self, task_id: str | Any, repo: str | None = None) -> dict[str, Any]:
        """Create a PR for a completed task"""
        self._validate_token()

        # Handle task_id being a Column object from SQLAlchemy if needed
        actual_task_id = str(task_id)

        task = self.db.query(GitHubTask).filter(GitHubTask.id == actual_task_id).first()
        if not task:
            raise PRCreationError(f"Task {task_id} not found")

        if task.status != "completed":
            raise PRCreationError(
                f"Task must be completed before creating PR (current status: {task.status})"
            )

        if task.github_pr_number:
            return {
                "message": "PR already exists",
                "pr_number": task.github_pr_number,
                "success": True,
            }

        repo_to_use = repo or task.github_repo
        owner, repo_name = self._get_repo_info(repo_to_use)

        # Prepare PR data
        pr_title = f"feat: {task.title}"
        pr_body = self._generate_pr_description(task)

        headers = {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github.v3+json",
        }

        pr_data = {
            "title": pr_title,
            "body": pr_body,
            "head": task.branch_name or f"task-{task.github_issue_number}",
            "base": "main",
        }

        # Create PR
        create_url = f"https://api.github.com/repos/{owner}/{repo_name}/pulls"

        try:
            response = requests.post(
                create_url, headers=headers, json=pr_data, timeout=30
            )
            response.raise_for_status()
            pr_result = response.json()
        except Exception as e:
            logger.error(f"Failed to create PR for task {task_id}: {str(e)}")
            return {"success": False, "error": str(e)}

        pr_number = pr_result["number"]
        pr_url = pr_result["html_url"]

        # Update task with PR number
        task.github_pr_number = pr_number
        task.updated_at = datetime.utcnow()

        try:
            self.db.commit()
        except Exception as e:
            self.db.rollback()
            logger.error(f"Failed to update task with PR number: {str(e)}")
            return {
                "success": True,
                "message": "PR created but task update failed",
                "pr_number": pr_number,
                "pr_url": pr_url,
            }

        return {
            "success": True,
            "message": "PR created successfully",
            "pr_number": pr_number,
            "pr_url": pr_url,
            "task_id": task_id,
        }

    def get_pr_status(
        self,
        task_id: str | None = None,
        repo: str | None = None,
        pr_number: int | None = None,
    ) -> dict[str, Any]:
        """Get status of a Pull Request"""
        self._validate_token()

        if task_id:
            task = self.db.query(GitHubTask).filter(GitHubTask.id == task_id).first()
            if task and task.github_pr_number:
                pr_number = task.github_pr_number
                repo = repo or task.github_repo

        if not pr_number or not repo:
            return {"error": "Missing PR number or repository", "success": False}

        owner, repo_name = self._get_repo_info(repo)
        url = f"https://api.github.com/repos/{owner}/{repo_name}/pulls/{pr_number}"
        headers = {"Authorization": f"token {self.token}"}

        try:
            response = requests.get(url, headers=headers, timeout=30)
            response.raise_for_status()
            data = response.json()
            # Compatibility with tests
            result = data.copy()
            result["pr_number"] = data.get("number")
            result["success"] = True
            return result
        except Exception as e:
            return {"success": False, "error": str(e)}

    def list_prs_for_repo(
        self, repo: str, status: str = "open"
    ) -> list[dict[str, Any]]:
        """List Pull Requests for a repository"""
        self._validate_token()
        owner, repo_name = self._get_repo_info(repo)

        url = f"https://api.github.com/repos/{owner}/{repo_name}/pulls"
        params = {"state": status}
        headers = {"Authorization": f"token {self.token}"}

        try:
            response = requests.get(url, headers=headers, params=params, timeout=30)
            response.raise_for_status()
            return response.json()
        except Exception as e:
            logger.error(f"Failed to list PRs: {e}")
            return []

    def auto_create_prs_for_completed(self, repo: str | None = None) -> dict[str, Any]:
        """Automatically create PRs for all completed tasks that don't have one"""
        query = self.db.query(GitHubTask).filter(
            GitHubTask.status == "completed", GitHubTask.github_pr_number == None
        )
        if repo:
            query = query.filter(GitHubTask.github_repo == repo)

        tasks = query.all()
        created = 0
        results = []
        for task in tasks:
            try:
                res = self.create_pr(task.id)
                if res.get("success"):
                    created += 1
                results.append(res)
            except Exception as e:
                logger.error(f"Failed to auto-create PR for task {task.id}: {str(e)}")
                results.append({"task_id": task.id, "error": str(e)})

        return {"created": created, "results": results, "success": True}

    def create_pr_from_issue(
        self,
        github_issue_number: int | None = None,
        repo: str | None = None,
        issue_number: int | None = None,
    ) -> dict[str, Any]:
        """Create PR from a GitHub issue by finding its task"""
        self._validate_token()

        issue_num = github_issue_number or issue_number

        task = (
            self.db.query(GitHubTask)
            .filter(
                GitHubTask.github_issue_number == issue_num,
                GitHubTask.github_repo == repo,
                GitHubTask.status == "completed",
            )
            .first()
        )

        if not task:
            raise PRCreationError(
                f"No completed task found for issue #{issue_num} in {repo}"
            )

        return self.create_pr(task.id)


# Dependency
async def get_pr_creator(db: Session = Depends(get_db)) -> PRCreator:
    """Get PR creator instance"""
    return PRCreator(db)


@router.post("/create/{task_id}")
async def create_pr_endpoint(
    task_id: str, pr_creator: PRCreator = Depends(get_pr_creator)
) -> dict[str, Any]:
    """Create a PR for a completed task"""
    try:
        result = pr_creator.create_pr(task_id)
        return result
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"PR creation endpoint error: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/create/from-issue/{issue_number}")
async def create_pr_from_issue_endpoint(
    issue_number: int,
    repo: str,
    pr_creator: PRCreator = Depends(get_pr_creator),
) -> dict[str, Any]:
    """Create a PR from a GitHub issue number"""
    try:
        result = pr_creator.create_pr_from_issue(issue_number, repo)
        return result
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"PR creation from issue failed: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/status/{task_id}")
async def get_pr_status(
    task_id: str,
    repo: str | None = None,
    pr_creator: PRCreator = Depends(get_pr_creator),
) -> dict[str, Any]:
    """Get PR status for a task"""
    try:
        result = pr_creator.get_pr_status(task_id=task_id, repo=repo)
        return result
    except Exception as e:
        logger.error(f"Failed to get PR status: {e}")
        return {"error": str(e), "success": False}


@router.get("/list/{repo:path}")
async def list_prs_for_repo(
    repo: str, state: str = "open", pr_creator: PRCreator = Depends(get_pr_creator)
) -> list[dict[str, Any]]:
    """List PRs created by the system for a repo"""
    try:
        return pr_creator.list_prs_for_repo(repo, state)
    except Exception as e:
        logger.error(f"Failed to list PRs: {e}")
        return []


@router.post("/auto-create-all")
async def auto_create_prs_for_completed(
    repo: str, pr_creator: PRCreator = Depends(get_pr_creator)
) -> dict[str, Any]:
    """Auto-create PRs for all completed tasks without PRs"""
    try:
        result = pr_creator.auto_create_prs_for_completed(repo)
        # Add "created" key for compatibility with some tests
        if "successful" in result:
            result["created"] = result["successful"]
        return result
    except Exception as e:
        logger.error(f"Auto-create PRs failed: {e}")
        return {"error": str(e), "success": False, "created": 0}


@router.get("/health")
async def pr_health_check() -> dict[str, Any]:
    """Health check for PR creation service"""
    return {
        "status": "healthy",
        "service": "pr_creation",
        "timestamp": datetime.utcnow().isoformat(),
        "github_configured": bool(get_settings().GITHUB_TOKEN),
    }
