"""vector_alpha_incident_fields

Revision ID: 4c27026a0fc0
Revises: 85efc23dfdcf
Create Date: 2026-03-29 12:04:03.637560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c27026a0fc0'
down_revision: Union[str, Sequence[str], None] = '85efc23dfdcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_tasks', sa.Column('validation_report', sa.JSON(), nullable=True))
    op.add_column('github_tasks', sa.Column('sandbox_result', sa.JSON(), nullable=True))
    op.add_column('incident_memory', sa.Column('repair_branch', sa.String(length=256), nullable=True))
    op.add_column('incident_memory', sa.Column('pr_url', sa.String(length=512), nullable=True))
    op.add_column('incident_memory', sa.Column('fix_status', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident_memory', 'fix_status')
    op.drop_column('incident_memory', 'pr_url')
    op.drop_column('incident_memory', 'repair_branch')
    op.drop_column('github_tasks', 'sandbox_result')
    op.drop_column('github_tasks', 'validation_report')
    # ### end Alembic commands ###
