"""vector_alpha_incident_fields

Revision ID: 4c27026a0fc0
Revises: 85efc23dfdcf
Create Date: 2026-03-29 12:04:03.637560

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4c27026a0fc0'
down_revision: Union[str, Sequence[str], None] = '85efc23dfdcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("incident_memory", sa.Column("repair_branch", sa.String(length=255), nullable=True))
    op.add_column("incident_memory", sa.Column("pr_url", sa.String(length=1024), nullable=True))
    op.add_column("incident_memory", sa.Column("fix_status", sa.String(length=50), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incident_memory", "fix_status")
    op.drop_column("incident_memory", "pr_url")
    op.drop_column("incident_memory", "repair_branch")
