"""add_vector_gamma_memory_models

Revision ID: 85efc23dfdcf
Revises: ea428b0c4e2a
Create Date: 2026-03-29 09:36:09.379436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85efc23dfdcf'
down_revision: Union[str, Sequence[str], None] = 'ea428b0c4e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('architecture_memory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('component_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('knowledge_factors', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architecture_memory_component_name'), 'architecture_memory', ['component_name'], unique=False)
    op.create_table('autonomy_cycle_memory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cycle_id', sa.String(length=128), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('tasks_processed', sa.Integer(), nullable=True),
    sa.Column('approvals_processed', sa.Integer(), nullable=True),
    sa.Column('errors_encountered', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autonomy_cycle_memory_cycle_id'), 'autonomy_cycle_memory', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_autonomy_cycle_memory_start_time'), 'autonomy_cycle_memory', ['start_time'], unique=False)
    op.create_table('incident_memory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_type', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('resolution_strategy', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_memory_incident_type'), 'incident_memory', ['incident_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_memory_incident_type'), table_name='incident_memory')
    op.drop_table('incident_memory')
    op.drop_index(op.f('ix_autonomy_cycle_memory_start_time'), table_name='autonomy_cycle_memory')
    op.drop_index(op.f('ix_autonomy_cycle_memory_cycle_id'), table_name='autonomy_cycle_memory')
    op.drop_table('autonomy_cycle_memory')
    op.drop_index(op.f('ix_architecture_memory_component_name'), table_name='architecture_memory')
    op.drop_table('architecture_memory')
    # ### end Alembic commands ###
