"""Add github_delivery_id to task_approvals

Revision ID: ea428b0c4e2a
Revises: 7d8e9f0a1b2c
Create Date: 2026-03-29 08:49:31.788255

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea428b0c4e2a"
down_revision: Union[str, Sequence[str], None] = "7d8e9f0a1b2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_approvals",
        sa.Column("last_github_delivery_id", sa.String(length=128), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_approvals", "last_github_delivery_id")
    # ### end Alembic commands ###
