"""Add goal and memory models

Revision ID: daae8c594417
Revises: 7076235fa3b6
Create Date: 2025-06-13 22:49:39.857594

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'daae8c594417'
down_revision: str | None = '7076235fa3b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_steps_id'), table_name='plan_steps')
    op.drop_table('plan_steps')
    op.drop_index(op.f('ix_core_memories_id'), table_name='core_memories')
    op.drop_index(op.f('ix_core_memories_memory_type'), table_name='core_memories')
    op.drop_index(op.f('ix_core_memories_title'), table_name='core_memories')
    op.drop_table('core_memories')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_memory_sentiments_emotion'), table_name='memory_sentiments')
    op.drop_index(op.f('ix_memory_sentiments_id'), table_name='memory_sentiments')
    op.drop_table('memory_sentiments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_sentiments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('memory_id', sa.INTEGER(), nullable=False),
    sa.Column('emotion', sa.VARCHAR(length=50), nullable=False),
    sa.Column('intensity', sa.INTEGER(), nullable=True),
    sa.Column('source_text_span', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['core_memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_sentiments_id'), 'memory_sentiments', ['id'], unique=False)
    op.create_index(op.f('ix_memory_sentiments_emotion'), 'memory_sentiments', ['emotion'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_table('core_memories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('memory_type', sa.VARCHAR(length=19), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('embedding', sqlite.JSON(), nullable=True),
    sa.Column('memory_metadata', sqlite.JSON(), nullable=True),
    sa.Column('related_to_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('accessed_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['related_to_id'], ['core_memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_memories_title'), 'core_memories', ['title'], unique=False)
    op.create_index(op.f('ix_core_memories_memory_type'), 'core_memories', ['memory_type'], unique=False)
    op.create_index(op.f('ix_core_memories_id'), 'core_memories', ['id'], unique=False)
    op.create_table('plan_steps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('goal_id', sa.INTEGER(), nullable=False),
    sa.Column('step_number', sa.INTEGER(), nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('parameters', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('result', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_steps_id'), 'plan_steps', ['id'], unique=False)
    # ### end Alembic commands ###
