"""add_core_memories_table

Revision ID: df8dc2b048ef
Revises: f2284b72eb0f
Create Date: 2025-06-04 08:55:09.395955

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df8dc2b048ef"
down_revision: Union[str, None] = "f2284b72eb0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "core_memories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_core_memories_id"), "core_memories", ["id"], unique=False)
    op.create_index(
        op.f("ix_core_memories_title"), "core_memories", ["title"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_core_memories_title"), table_name="core_memories")
    op.drop_index(op.f("ix_core_memories_id"), table_name="core_memories")
    op.drop_table("core_memories")
    # ### end Alembic commands ###
