"""create_core_memories_table

Revision ID: f2284b72eb0f
Revises:
Create Date: 2025-06-04 08:52:49.953281

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "f2284b72eb0f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
